version: '3'

tasks:
  server:
    env:
      CONFIG_PATH: ./config/server.yaml
    cmds:
      - go run ./cmd/db
  client:
    cmds:
      - go run ./cmd/client --address={{.SERVER_ADDRESS}}
  lint:
    cmds:
      - golangci-lint run
  test:
    cmds:
      - go test -race -count=1 -timeout 30s ./...
  build:
    cmds:
      - go build -o ./bin/db ./cmd/db
      - go build -o ./bin/client ./cmd/client
  clean:
    cmds:
      - rm -rf ./bin
