// Code generated by mockery v2.53.3. DO NOT EDIT.

package storage

import (
	wal "github.com/DaniilZ77/InMemDB/internal/storage/wal"
	mock "github.com/stretchr/testify/mock"
)

// MockWal is an autogenerated mock type for the Wal type
type MockWal struct {
	mock.Mock
}

type MockWal_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWal) EXPECT() *MockWal_Expecter {
	return &MockWal_Expecter{mock: &_m.Mock}
}

// Recover provides a mock function with no fields
func (_m *MockWal) Recover() ([]wal.Command, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Recover")
	}

	var r0 []wal.Command
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]wal.Command, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []wal.Command); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]wal.Command)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWal_Recover_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Recover'
type MockWal_Recover_Call struct {
	*mock.Call
}

// Recover is a helper method to define mock.On call
func (_e *MockWal_Expecter) Recover() *MockWal_Recover_Call {
	return &MockWal_Recover_Call{Call: _e.mock.On("Recover")}
}

func (_c *MockWal_Recover_Call) Run(run func()) *MockWal_Recover_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWal_Recover_Call) Return(_a0 []wal.Command, _a1 error) *MockWal_Recover_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWal_Recover_Call) RunAndReturn(run func() ([]wal.Command, error)) *MockWal_Recover_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWal creates a new instance of MockWal. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWal(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWal {
	mock := &MockWal{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
