engine:
  type: "in_memory"
  shards_number: 16
network:
  address: "0.0.0.0:3224"
  max_connections: 100
  max_message_size: "4KB"
  idle_timeout: 5m
log_level: info
wal:
  flushing_batch_size: 100
  flushing_batch_timeout: 10ms
  max_segment_size: "1KB"
  data_directory: ./tests/testdata/replica_wal
replication:
  replica_type: "slave"
  master_address: "master:3232"
  sync_interval: "1s"
