// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Database is an autogenerated mock type for the Database type
type Database struct {
	mock.Mock
}

type Database_Expecter struct {
	mock *mock.Mock
}

func (_m *Database) EXPECT() *Database_Expecter {
	return &Database_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: source
func (_m *Database) Execute(source string) string {
	ret := _m.Called(source)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(source)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Database_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type Database_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - source string
func (_e *Database_Expecter) Execute(source interface{}) *Database_Execute_Call {
	return &Database_Execute_Call{Call: _e.mock.On("Execute", source)}
}

func (_c *Database_Execute_Call) Run(run func(source string)) *Database_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Database_Execute_Call) Return(_a0 string) *Database_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Database_Execute_Call) RunAndReturn(run func(string) string) *Database_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewDatabase creates a new instance of Database. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDatabase(t interface {
	mock.TestingT
	Cleanup(func())
}) *Database {
	mock := &Database{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
