// Code generated by mockery v2.53.3. DO NOT EDIT.

package wal

import mock "github.com/stretchr/testify/mock"

// MockLogsReader is an autogenerated mock type for the LogsReader type
type MockLogsReader struct {
	mock.Mock
}

type MockLogsReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLogsReader) EXPECT() *MockLogsReader_Expecter {
	return &MockLogsReader_Expecter{mock: &_m.Mock}
}

// Read provides a mock function with no fields
func (_m *MockLogsReader) Read() ([]Command, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 []Command
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]Command, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []Command); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Command)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLogsReader_Read_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Read'
type MockLogsReader_Read_Call struct {
	*mock.Call
}

// Read is a helper method to define mock.On call
func (_e *MockLogsReader_Expecter) Read() *MockLogsReader_Read_Call {
	return &MockLogsReader_Read_Call{Call: _e.mock.On("Read")}
}

func (_c *MockLogsReader_Read_Call) Run(run func()) *MockLogsReader_Read_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockLogsReader_Read_Call) Return(_a0 []Command, _a1 error) *MockLogsReader_Read_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLogsReader_Read_Call) RunAndReturn(run func() ([]Command, error)) *MockLogsReader_Read_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLogsReader creates a new instance of MockLogsReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLogsReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLogsReader {
	mock := &MockLogsReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
