// Code generated by mockery v2.53.3. DO NOT EDIT.

package mvcc

import mock "github.com/stretchr/testify/mock"

// MockEngine is an autogenerated mock type for the Engine type
type MockEngine struct {
	mock.Mock
}

type MockEngine_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEngine) EXPECT() *MockEngine_Expecter {
	return &MockEngine_Expecter{mock: &_m.Mock}
}

// ExistsBetween provides a mock function with given fields: beginTxID, endTxID, key
func (_m *MockEngine) ExistsBetween(beginTxID int64, endTxID int64, key string) bool {
	ret := _m.Called(beginTxID, endTxID, key)

	if len(ret) == 0 {
		panic("no return value specified for ExistsBetween")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(int64, int64, string) bool); ok {
		r0 = rf(beginTxID, endTxID, key)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockEngine_ExistsBetween_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExistsBetween'
type MockEngine_ExistsBetween_Call struct {
	*mock.Call
}

// ExistsBetween is a helper method to define mock.On call
//   - beginTxID int64
//   - endTxID int64
//   - key string
func (_e *MockEngine_Expecter) ExistsBetween(beginTxID interface{}, endTxID interface{}, key interface{}) *MockEngine_ExistsBetween_Call {
	return &MockEngine_ExistsBetween_Call{Call: _e.mock.On("ExistsBetween", beginTxID, endTxID, key)}
}

func (_c *MockEngine_ExistsBetween_Call) Run(run func(beginTxID int64, endTxID int64, key string)) *MockEngine_ExistsBetween_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64), args[1].(int64), args[2].(string))
	})
	return _c
}

func (_c *MockEngine_ExistsBetween_Call) Return(_a0 bool) *MockEngine_ExistsBetween_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEngine_ExistsBetween_Call) RunAndReturn(run func(int64, int64, string) bool) *MockEngine_ExistsBetween_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: txID, key
func (_m *MockEngine) Get(txID int64, key string) (string, bool) {
	ret := _m.Called(txID, key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 string
	var r1 bool
	if rf, ok := ret.Get(0).(func(int64, string) (string, bool)); ok {
		return rf(txID, key)
	}
	if rf, ok := ret.Get(0).(func(int64, string) string); ok {
		r0 = rf(txID, key)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(int64, string) bool); ok {
		r1 = rf(txID, key)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// MockEngine_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockEngine_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - txID int64
//   - key string
func (_e *MockEngine_Expecter) Get(txID interface{}, key interface{}) *MockEngine_Get_Call {
	return &MockEngine_Get_Call{Call: _e.mock.On("Get", txID, key)}
}

func (_c *MockEngine_Get_Call) Run(run func(txID int64, key string)) *MockEngine_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64), args[1].(string))
	})
	return _c
}

func (_c *MockEngine_Get_Call) Return(_a0 string, _a1 bool) *MockEngine_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEngine_Get_Call) RunAndReturn(run func(int64, string) (string, bool)) *MockEngine_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function with given fields: txID, key, value
func (_m *MockEngine) Set(txID int64, key string, value *string) {
	_m.Called(txID, key, value)
}

// MockEngine_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockEngine_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - txID int64
//   - key string
//   - value *string
func (_e *MockEngine_Expecter) Set(txID interface{}, key interface{}, value interface{}) *MockEngine_Set_Call {
	return &MockEngine_Set_Call{Call: _e.mock.On("Set", txID, key, value)}
}

func (_c *MockEngine_Set_Call) Run(run func(txID int64, key string, value *string)) *MockEngine_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64), args[1].(string), args[2].(*string))
	})
	return _c
}

func (_c *MockEngine_Set_Call) Return() *MockEngine_Set_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockEngine_Set_Call) RunAndReturn(run func(int64, string, *string)) *MockEngine_Set_Call {
	_c.Run(run)
	return _c
}

// SetMany provides a mock function with given fields: txID, modified
func (_m *MockEngine) SetMany(txID int64, modified map[string]*string) {
	_m.Called(txID, modified)
}

// MockEngine_SetMany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetMany'
type MockEngine_SetMany_Call struct {
	*mock.Call
}

// SetMany is a helper method to define mock.On call
//   - txID int64
//   - modified map[string]*string
func (_e *MockEngine_Expecter) SetMany(txID interface{}, modified interface{}) *MockEngine_SetMany_Call {
	return &MockEngine_SetMany_Call{Call: _e.mock.On("SetMany", txID, modified)}
}

func (_c *MockEngine_SetMany_Call) Run(run func(txID int64, modified map[string]*string)) *MockEngine_SetMany_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64), args[1].(map[string]*string))
	})
	return _c
}

func (_c *MockEngine_SetMany_Call) Return() *MockEngine_SetMany_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockEngine_SetMany_Call) RunAndReturn(run func(int64, map[string]*string)) *MockEngine_SetMany_Call {
	_c.Run(run)
	return _c
}

// NewMockEngine creates a new instance of MockEngine. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEngine(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEngine {
	mock := &MockEngine{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
