// Code generated by mockery v2.53.3. DO NOT EDIT.

package mvcc

import (
	parser "github.com/DaniilZ77/InMemDB/internal/compute/parser"
	mock "github.com/stretchr/testify/mock"
)

// MockWal is an autogenerated mock type for the Wal type
type MockWal struct {
	mock.Mock
}

type MockWal_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWal) EXPECT() *MockWal_Expecter {
	return &MockWal_Expecter{mock: &_m.Mock}
}

// Save provides a mock function with given fields: txID, command
func (_m *MockWal) Save(txID int64, command *parser.Command) bool {
	ret := _m.Called(txID, command)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(int64, *parser.Command) bool); ok {
		r0 = rf(txID, command)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockWal_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockWal_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - txID int64
//   - command *parser.Command
func (_e *MockWal_Expecter) Save(txID interface{}, command interface{}) *MockWal_Save_Call {
	return &MockWal_Save_Call{Call: _e.mock.On("Save", txID, command)}
}

func (_c *MockWal_Save_Call) Run(run func(txID int64, command *parser.Command)) *MockWal_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64), args[1].(*parser.Command))
	})
	return _c
}

func (_c *MockWal_Save_Call) Return(_a0 bool) *MockWal_Save_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWal_Save_Call) RunAndReturn(run func(int64, *parser.Command) bool) *MockWal_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWal creates a new instance of MockWal. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWal(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWal {
	mock := &MockWal{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
