engine:
  type: "in_memory"
  shards_number: 16
network:
  max_connections: 1000
  max_message_size: "4KB"
  idle_timeout: 5m
log_level: info
wal:
  flushing_batch_size: 100
  flushing_batch_timeout: 10ms
  max_segment_size: "10MB"
replication:
  master_address: "127.0.0.1:3232"
  sync_interval: "1s"
