// Code generated by mockery v2.50.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// BaseEngine is an autogenerated mock type for the BaseEngine type
type BaseEngine struct {
	mock.Mock
}

// Del provides a mock function with given fields: key
func (_m *BaseEngine) Del(key string) {
	_m.Called(key)
}

// Get provides a mock function with given fields: key
func (_m *BaseEngine) Get(key string) (*string, error) {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*string, error)); ok {
		return rf(key)
	}
	if rf, ok := ret.Get(0).(func(string) *string); ok {
		r0 = rf(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*string)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Set provides a mock function with given fields: key, value
func (_m *BaseEngine) Set(key string, value string) {
	_m.Called(key, value)
}

// NewBaseEngine creates a new instance of BaseEngine. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBaseEngine(t interface {
	mock.TestingT
	Cleanup(func())
}) *BaseEngine {
	mock := &BaseEngine{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
